services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - DOCKER_LOCAL=true
  frontend:
    build:
      context: ../codehive-frontend
      dockerfile: Dockerfile
      args:
        ENV_FILE: ".env.development"
    ports:
      - "3000:3000"
    env_file:
      - ../codehive-frontend/.env.local
    environment:
      - DOCKER_LOCAL=true
    profiles:
      - frontend-and-backend