# Generated by Django 5.1.1 on 2024-10-02 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.UUIDField(primary_key=True, serialize=False)),
                ('public', models.BooleanField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('pfp_url', models.TextField(blank=True, null=True)),
                ('reputation', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.projects')),
                ('asker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.users')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.users'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.UUIDField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse.users')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
