# Generated by Django 5.1.1 on 2024-10-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0002_users_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='test',
        ),
    ]
