# Generated by Django 5.1.1 on 2024-10-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0005_answers_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='delete_me_pls_god',
            field=models.TextField(null=True),
        ),
    ]
