# Generated by Django 5.1.1 on 2024-10-08 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0006_answers_delete_me_pls_god'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='delete_me_pls_god',
        ),
    ]
