# Generated by Django 5.1.1 on 2024-10-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0009_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commnent_id',
            new_name='comment_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='answer_id',
        ),
        migrations.AddField(
            model_name='comments',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.answers'),
        ),
    ]
