# Generated by Django 5.1.1 on 2024-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0009_tags_projects_tags_questions_tags'),
        ('pulse', '0010_rename_commnent_id_comments_comment_id_and_more'),
    ]

    operations = [
    ]
