# Generated by Django 5.1.1 on 2024-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0011_merge_20241014_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='pulse.tags'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='pulse.tags'),
        ),
    ]
