# Generated by Django 5.1.1 on 2024-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0012_alter_projects_tags_alter_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='repo_full_name',
            field=models.TextField(null=True),
        ),
    ]
