# Generated by Django 5.1.2 on 2024-10-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0010_alter_projects_tags_alter_questions_tags'),
        ('pulse', '0013_projects_repo_full_name'),
    ]

    operations = [
    ]
