# Generated by Django 5.1.2 on 2024-10-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0013_projects_repo_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
