# Generated by Django 5.1.2 on 2024-11-03 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_users_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pfp_url',
        ),
    ]
