# Generated by Django 5.1.2 on 2024-10-26 17:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_merge_20241018_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Questions_search__5ab0e5_gin'),
        ),
    ]
