# Generated by Django 5.1.2 on 2024-10-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0015_questions_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='code_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='code_context_full_pathname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='code_context_line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
