# Generated by Django 5.1.2 on 2024-10-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0014_answers_score_votes'),
        ('pulse', '0015_questions_search_vector_and_more'),
    ]

    operations = [
    ]
