# Generated by Django 5.1.2 on 2024-10-27 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0017_alter_votes_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.answers'),
        ),
    ]
