# Generated by Django 5.1.2 on 2024-10-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0016_questions_code_context_and_more'),
        ('pulse', '0018_alter_votes_answer'),
    ]

    operations = [
    ]
