# Generated by Django 5.1.2 on 2024-10-29 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0019_merge_20241028_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communities',
            fields=[
                ('community_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('member_count', models.BigIntegerField(default=0)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='communities', to='pulse.tags')),
            ],
            options={
                'db_table': 'Communities',
            },
        ),
        migrations.CreateModel(
            name='CommunityMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.communities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.users')),
            ],
            options={
                'db_table': 'CommunityMembers',
                'constraints': [models.UniqueConstraint(fields=('community', 'user'), name='unique_community_user')],
            },
        ),
    ]
