# Generated by Django 5.1.2 on 2024-10-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0021_communities_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
