# Generated by Django 5.1.2 on 2024-11-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0015_remove_users_pfp_url'),
        ('pulse', '0023_alter_communities_avatar_url'),
    ]

    operations = [
    ]
