# Generated by Django 5.1.2 on 2024-11-03 16:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0023_alter_communities_avatar_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='questions',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='questions',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='description_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
