# Generated by Django 5.1.2 on 2024-11-03 17:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0024_questions_title_trgm_questions_description_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tags',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='tags_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
