# Generated by Django 5.1.2 on 2024-11-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0025_communitymembers_community_reputation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembers',
            name='contributions',
            field=models.BigIntegerField(default=0),
        ),
    ]
