# Generated by Django 5.1.2 on 2024-11-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0024_merge_20241104_0216'),
        ('pulse', '0026_communitymembers_contributions'),
    ]

    operations = [
    ]
