# Generated by Django 5.1.2 on 2024-11-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0025_tags_tags_name_trgm'),
        ('pulse', '0027_merge_20241104_1114'),
    ]

    operations = [
    ]
