# Generated by Django 5.1.3 on 2024-11-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0035_notifications_community_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_answered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
