# Generated by Django 5.1.3 on 2024-11-25 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0035_notifications_community_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('badge_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('reputation_threshold', models.IntegerField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, default='https://cdn-icons-png.flaticon.com/512/20/20100.png', null=True)),
                ('associated_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='pulse.tags')),
            ],
            options={
                'db_table': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.users')),
            ],
            options={
                'db_table': 'UserBadges',
            },
        ),
        migrations.CreateModel(
            name='UserBadgeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.BigIntegerField(default=0)),
                ('progress_target', models.BigIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulse.users')),
            ],
            options={
                'db_table': 'UserBadgeProgress',
            },
        ),
        migrations.AddConstraint(
            model_name='badge',
            constraint=models.CheckConstraint(condition=models.Q(('associated_tag__isnull', True), ('is_global', False), _connector='OR'), name='mutual_exclusivity_check'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='userbadgeprogress',
            unique_together={('user', 'badge')},
        ),
    ]
