# Generated by Django 5.1.3 on 2024-11-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0036_badge_userbadge_userbadgeprogress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('reputation_threshold', models.PositiveIntegerField()),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pulse.badge')),
            ],
            options={
                'ordering': ['badge', 'tier_level'],
                'unique_together': {('badge', 'tier_level')},
            },
        ),
        migrations.AddField(
            model_name='userbadge',
            name='badge_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pulse.badgetier'),
        ),
    ]
