# Generated by Django 5.1.2 on 2024-11-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0036_badge_userbadge_userbadgeprogress_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badge',
            table='Badges',
        ),
        migrations.AlterModelTable(
            name='userbadge',
            table='UserBadges',
        ),
        migrations.AlterModelTable(
            name='userbadgeprogress',
            table='UserBadgeProgress',
        ),
    ]
