# Generated by Django 5.1.2 on 2024-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0037_alter_badge_table_alter_userbadge_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='image_url',
            field=models.URLField(blank=True, default='https://example.com/images/default-badge.png', null=True),
        ),
    ]
