# Generated by Django 5.1.3 on 2024-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0037_badgetier_userbadge_badge_tier'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='badgetier',
            table='BadgeTier',
        ),
    ]
