# Generated by Django 5.1.3 on 2024-11-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0038_alter_badgetier_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='reputation_threshold',
        ),
    ]
