# Generated by Django 5.1.3 on 2024-12-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0037_alter_questions_is_answered'),
        ('pulse', '0039_remove_badge_reputation_threshold'),
    ]

    operations = [
    ]
