# Generated by Django 5.1.3 on 2024-12-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0039_questions_view_count'),
        ('pulse', '0039_remove_questions_related_community_and_more'),
    ]

    operations = [
    ]
