# Generated by Django 5.1.3 on 2024-12-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0040_merge_20241209_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='code_context_line_number',
            new_name='code_context_line_number_start',
        ),
        migrations.AddField(
            model_name='questions',
            name='code_context_line_number_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
