# Generated by Django 5.1.3 on 2024-12-02 18:15

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0041_alter_badge_badge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgetier',
            name='id',
        ),
        migrations.AddField(
            model_name='badgetier',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='id',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='userbadgeprogress',
            name='id',
        ),
        migrations.AddField(
            model_name='userbadgeprogress',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
    ]
