name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate Docker with Google Cloud
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-app:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-app:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-app \
          --image gcr.io/${{ secrets.GOOGLE_CLOUD_PROJECT }}/my-app:${{ github.sha }} \
          --region us-east4 \
          --platform managed \
          --allow-unauthenticated=false \  # Disables public access to the API
          --ingress internal-and-cloud-load-balancing \  # Restrict ingress to internal traffic and cloud load balancing
          --set-cloudsql-instances YOUR_INSTANCE_CONNECTION_NAME \  # Optionally restrict ingress traffic further
          --no-cpu-throttling \  # Ensure CPU is allocated only during request processing
          --min-instances 1 \  # Set minimum number of instances to 1
          --max-instances 10 \  # Adjust this based on your scaling needs
          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} \
          --vpc-egress all \
          --port 8080  # Port 8080 the set port by Google Cloud Run